// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx_0xX4OdM5KnM8I_I_zgmVv62o3Ah6_Y',
    appId: '1:329244160825:web:e29fa57bc5bc894587eee8',
    messagingSenderId: '329244160825',
    projectId: 'green-b0d7b',
    authDomain: 'green-b0d7b.firebaseapp.com',
    storageBucket: 'green-b0d7b.firebasestorage.app',
    measurementId: 'G-567Y6XTMTX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb1M5YaITTLYwV51LvJdAKtoTQMqcb6wU',
    appId: '1:329244160825:android:e70e409103c4cb5d87eee8',
    messagingSenderId: '329244160825',
    projectId: 'green-b0d7b',
    storageBucket: 'green-b0d7b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvK7yfb1v3qcHLacu6YDNJc-gxC-zltxo',
    appId: '1:329244160825:ios:957af1e372f15ba187eee8',
    messagingSenderId: '329244160825',
    projectId: 'green-b0d7b',
    storageBucket: 'green-b0d7b.firebasestorage.app',
    iosBundleId: 'com.example.greenlist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvK7yfb1v3qcHLacu6YDNJc-gxC-zltxo',
    appId: '1:329244160825:ios:957af1e372f15ba187eee8',
    messagingSenderId: '329244160825',
    projectId: 'green-b0d7b',
    storageBucket: 'green-b0d7b.firebasestorage.app',
    iosBundleId: 'com.example.greenlist',
  );
}
